# Generated by Django 4.2.1 on 2023-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alcohol_intake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_activity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoker',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diastolic_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glucose',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='systolic_pressure',
            field=models.FloatField(),
        ),
    ]
